import { COMMON_WIN32_ABI } from '../../vm86/abi';

/**
 * Red Alert 2 / XWIS 轻量客户端的独立 x86 ABI。
 *
 * 网络、外层 WOL UI 和 Bink 在单机阶段只走最小失败/跳过语义，但仍必须登记
 * 正确的 `ret n`，否则一次可选功能探测就会把客体栈永久推歪。XWIS ord1 的
 * 唯一导出为 `?X@@YAXXZ`（无参数 cdecl），因此清理字节数为 0。
 */
export const RA2_ABI: Record<string, number> = {
  ...COMMON_WIN32_ABI,
  'XWIS.DLL!ord1': 0,

  'KERNEL32.DLL!GetTickCount': 0,
  'KERNEL32.DLL!GetEnvironmentVariableA': 12,
  'KERNEL32.DLL!SetErrorMode': 4,
  'KERNEL32.DLL!GetSystemDirectoryA': 8,
  'KERNEL32.DLL!GetWindowsDirectoryA': 8,
  'KERNEL32.DLL!GlobalMemoryStatus': 4,
  'KERNEL32.DLL!VirtualQuery': 12,
  'KERNEL32.DLL!GetTimeFormatA': 24,
  'KERNEL32.DLL!GetDateFormatA': 24,
  'KERNEL32.DLL!FileTimeToSystemTime': 8,
  'KERNEL32.DLL!FileTimeToLocalFileTime': 8,
  'KERNEL32.DLL!SystemTimeToFileTime': 8,
  'KERNEL32.DLL!CompareFileTime': 8,
  'KERNEL32.DLL!FlushInstructionCache': 12,
  'KERNEL32.DLL!VirtualProtect': 16,
  'KERNEL32.DLL!CreateDirectoryA': 8,
  'KERNEL32.DLL!MulDiv': 12,
  'KERNEL32.DLL!EscapeCommFunction': 8,
  'KERNEL32.DLL!ClearCommBreak': 4,
  'KERNEL32.DLL!SetCommBreak': 4,
  'KERNEL32.DLL!GetFileSize': 8,
  'KERNEL32.DLL!FileTimeToDosDateTime': 12,
  'KERNEL32.DLL!GetFileInformationByHandle': 8,
  'KERNEL32.DLL!SetFileTime': 16,
  'KERNEL32.DLL!CopyFileA': 12,
  'KERNEL32.DLL!DeleteFileA': 4,
  'KERNEL32.DLL!lstrcatA': 8,
  'KERNEL32.DLL!lstrcpyA': 8,
  'KERNEL32.DLL!SetCurrentDirectoryA': 4,
  'KERNEL32.DLL!OpenMutexA': 12,
  'KERNEL32.DLL!GetFileTime': 16,
  'KERNEL32.DLL!GetLogicalDriveStringsA': 8,
  'KERNEL32.DLL!ClearCommError': 12,
  'KERNEL32.DLL!GetCommState': 8,
  'KERNEL32.DLL!PurgeComm': 8,
  'KERNEL32.DLL!SetupComm': 12,
  'KERNEL32.DLL!GetCommMask': 8,
  'KERNEL32.DLL!ResetEvent': 4,
  'KERNEL32.DLL!GetCommModemStatus': 8,
  'KERNEL32.DLL!GetOverlappedResult': 16,
  'KERNEL32.DLL!GetExitCodeProcess': 8,
  'KERNEL32.DLL!GetCurrentDirectoryA': 8,
  'KERNEL32.DLL!GetComputerNameA': 8,
  'KERNEL32.DLL!DosDateTimeToFileTime': 12,
  'KERNEL32.DLL!CreateProcessA': 40,
  'KERNEL32.DLL!FreeConsole': 0,
  'KERNEL32.DLL!DeviceIoControl': 32,
  'KERNEL32.DLL!QueryPerformanceCounter': 4,
  'KERNEL32.DLL!QueryPerformanceFrequency': 4,
  'KERNEL32.DLL!SetThreadPriority': 8,
  'KERNEL32.DLL!FormatMessageA': 28,
  'KERNEL32.DLL!FindFirstFileA': 8,
  'KERNEL32.DLL!FindNextFileA': 8,
  'KERNEL32.DLL!AllocConsole': 0,
  'KERNEL32.DLL!GetVolumeInformationA': 32,
  'KERNEL32.DLL!FreeLibrary': 4,
  'KERNEL32.DLL!LockResource': 4,
  'KERNEL32.DLL!FindResourceA': 12,
  'KERNEL32.DLL!LoadResource': 8,
  'KERNEL32.DLL!OpenEventA': 12,
  'KERNEL32.DLL!UnmapViewOfFile': 4,
  'KERNEL32.DLL!MapViewOfFileEx': 24,
  'KERNEL32.DLL!GetDiskFreeSpaceA': 20,
  'KERNEL32.DLL!SetCommTimeouts': 8,
  'KERNEL32.DLL!SetCommState': 8,
  'KERNEL32.DLL!GetLocalTime': 4,
  'KERNEL32.DLL!PeekConsoleInputA': 16,
  'KERNEL32.DLL!GetConsoleMode': 8,
  'KERNEL32.DLL!SetConsoleMode': 8,
  'KERNEL32.DLL!HeapSize': 12,
  'KERNEL32.DLL!GetFileAttributesA': 4,
  'KERNEL32.DLL!GetCurrentProcessId': 0,
  'KERNEL32.DLL!FindClose': 4,
  'KERNEL32.DLL!LocalFree': 4,
  'KERNEL32.DLL!lstrlenW': 4,
  'KERNEL32.DLL!RaiseException': 16,
  'KERNEL32.DLL!ReadConsoleInputA': 16,
  'KERNEL32.DLL!GetNumberOfConsoleInputEvents': 8,
  'KERNEL32.DLL!WriteConsoleA': 20,
  'KERNEL32.DLL!HeapValidate': 12,
  'KERNEL32.DLL!DebugBreak': 0,
  'KERNEL32.DLL!OutputDebugStringA': 4,

  'USER32.DLL!WindowFromPoint': 8,
  'USER32.DLL!GetClassLongA': 8,
  'USER32.DLL!ChangeDisplaySettingsA': 8,
  'USER32.DLL!GetWindowThreadProcessId': 8,
  'USER32.DLL!GetActiveWindow': 0,
  'USER32.DLL!ToAscii': 20,
  'USER32.DLL!ChildWindowFromPointEx': 16,
  'USER32.DLL!IsWindowEnabled': 4,
  'USER32.DLL!GetAsyncKeyState': 4,
  'USER32.DLL!DialogBoxParamA': 20,
  'USER32.DLL!DialogBoxIndirectParamA': 20,
  'USER32.DLL!MapVirtualKeyA': 8,
  'USER32.DLL!GetSystemMetrics': 4,
  'USER32.DLL!MoveWindow': 24,
  'USER32.DLL!ReleaseCapture': 0,
  'USER32.DLL!GetCapture': 0,
  'USER32.DLL!SetCapture': 4,
  'USER32.DLL!GetDlgCtrlID': 4,
  'USER32.DLL!ValidateRect': 8,
  'USER32.DLL!AdjustWindowRect': 12,
  'USER32.DLL!GetSysColor': 4,
  'USER32.DLL!IsDlgButtonChecked': 8,
  'USER32.DLL!CheckDlgButton': 12,
  'USER32.DLL!WaitForInputIdle': 8,
  'USER32.DLL!GetTopWindow': 4,
  'USER32.DLL!GetForegroundWindow': 0,
  'USER32.DLL!SetActiveWindow': 4,
  'USER32.DLL!RedrawWindow': 16,
  'USER32.DLL!GetWindowContextHelpId': 4,
  'USER32.DLL!WinHelpA': 16,
  'USER32.DLL!ChildWindowFromPoint': 12,
  'USER32.DLL!FindWindowA': 8,
  'USER32.DLL!SetCursorPos': 8,
  'USER32.DLL!CreateDialogIndirectParamA': 20,
  'USER32.DLL!GetKeyNameTextA': 12,
  'USER32.DLL!ScreenToClient': 8,
  'USER32.DLL!LockWindowUpdate': 4,
  'USER32.DLL!CloseWindow': 4,
  'USER32.DLL!GetFocus': 0,
  'USER32.DLL!MessageBoxIndirectA': 4,
  'USER32.DLL!GetUpdateRect': 12,
  'USER32.DLL!GetWindow': 8,
  'USER32.DLL!SendDlgItemMessageA': 20,
  'USER32.DLL!SetWindowLongA': 12,
  'USER32.DLL!EnableWindow': 8,
  'USER32.DLL!InvalidateRect': 12,
  'USER32.DLL!GetDlgItem': 8,
  'USER32.DLL!BringWindowToTop': 4,
  'USER32.DLL!CallWindowProcA': 20,
  'USER32.DLL!SetForegroundWindow': 4,
  'USER32.DLL!IsWindowVisible': 4,
  'USER32.DLL!EnumChildWindows': 12,
  'USER32.DLL!GetClassNameA': 12,
  'USER32.DLL!TranslateAcceleratorA': 12,
  'USER32.DLL!GetWindowTextA': 12,
  'USER32.DLL!CharToOemBuffA': 12,
  'USER32.DLL!GetNextDlgTabItem': 12,
  'USER32.DLL!GetParent': 4,
  'USER32.DLL!RegisterHotKey': 16,

  'GDI32.DLL!CreateSolidBrush': 4,
  'GDI32.DLL!GetTextColor': 4,
  'GDI32.DLL!GetBkMode': 4,
  'GDI32.DLL!GetBkColor': 4,
  'GDI32.DLL!DPtoLP': 12,
  'GDI32.DLL!SetWindowOrgEx': 16,
  'GDI32.DLL!RestoreDC': 8,
  'GDI32.DLL!ModifyWorldTransform': 12,
  'GDI32.DLL!SetGraphicsMode': 8,
  'GDI32.DLL!SetViewportOrgEx': 16,
  'GDI32.DLL!SaveDC': 4,
  'GDI32.DLL!CreateDIBSection': 24,
  'GDI32.DLL!GetTextMetricsA': 8,

  'ADVAPI32.DLL!RegQueryInfoKeyA': 48,
  'ADVAPI32.DLL!RegCloseKey': 4,
  'ADVAPI32.DLL!RegQueryValueExA': 24,
  'ADVAPI32.DLL!RegOpenKeyExA': 20,
  'ADVAPI32.DLL!RegDeleteValueA': 8,
  'ADVAPI32.DLL!RegSetValueExA': 24,
  'ADVAPI32.DLL!RegCreateKeyExA': 36,
  'ADVAPI32.DLL!RegEnumKeyExA': 32,
  'ADVAPI32.DLL!RegDeleteKeyA': 8,
  'SHELL32.DLL!FindExecutableA': 12,

  'OLE32.DLL!StgCreateDocfile': 16,
  'OLE32.DLL!CoRevokeClassObject': 4,
  'OLE32.DLL!OleUninitialize': 0,
  'OLE32.DLL!OleInitialize': 4,
  'OLE32.DLL!CoRegisterClassObject': 20,
  'OLE32.DLL!CoDisconnectObject': 8,
  'OLE32.DLL!StringFromGUID2': 12,
  'OLE32.DLL!StgOpenStorage': 24,
  'OLE32.DLL!CoFileTimeNow': 4,
  'OLE32.DLL!StringFromCLSID': 8,
  'OLE32.DLL!CLSIDFromString': 8,
  // OleSaveToStream(IPersistStream*, IStream*) 只有两个参数。错记成
  // 12 字节会让 stdcall 桩多弹一格，RA2 选择战役后保存 ALL01T
  // 初始状态时便会把返回地址当数据，最终落入 WASM unreachable。
  'OLE32.DLL!OleSaveToStream': 8,
  'OLE32.DLL!OleLoadFromStream': 12,
  'OLE32.DLL!OleRun': 4,

  'OLEAUT32.DLL!ord200': 8,
  'OLEAUT32.DLL!ord34': 8,
  'OLEAUT32.DLL!ord161': 8,
  'OLEAUT32.DLL!ord6': 4,
  'OLEAUT32.DLL!ord2': 4,
  'OLEAUT32.DLL!ord33': 16,
  'OLEAUT32.DLL!ord201': 8,
  'OLEAUT32.DLL!ord12': 16,
  'OLEAUT32.DLL!ord202': 4,
  'OLEAUT32.DLL!ord9': 4,
  'OLEAUT32.DLL!ord8': 4,
  'WINMM.DLL!timeGetTime': 0,

  'WSOCK32.DLL!ord7': 20,
  'WSOCK32.DLL!ord14': 4,
  'WSOCK32.DLL!ord9': 4,
  'WSOCK32.DLL!ord17': 24,
  'WSOCK32.DLL!ord8': 4,
  'WSOCK32.DLL!ord21': 20,
  'WSOCK32.DLL!ord20': 24,
  'WSOCK32.DLL!ord15': 4,
  'WSOCK32.DLL!ord57': 8,
  'WSOCK32.DLL!ord115': 8,
  'WSOCK32.DLL!ord1111': 12,
  'WSOCK32.DLL!ord101': 16,
  'WSOCK32.DLL!ord116': 0,
  'WSOCK32.DLL!ord111': 0,
  'WSOCK32.DLL!ord11': 4,
  'WSOCK32.DLL!ord23': 12,
  'WSOCK32.DLL!ord2': 12,
  'WSOCK32.DLL!ord3': 4,
  'WSOCK32.DLL!ord52': 4,

  'VERSION.DLL!VerQueryValueA': 16,
  'VERSION.DLL!GetFileVersionInfoSizeA': 8,
  'VERSION.DLL!GetFileVersionInfoA': 16,
  'COMCTL32.DLL!ImageList_DragShowNolock': 4,
  'COMCTL32.DLL!ord17': 0,
  'COMCTL32.DLL!ImageList_DragMove': 8,
  'COMCTL32.DLL!ImageList_DragEnter': 12,
  'COMCTL32.DLL!ImageList_BeginDrag': 16,
  'COMCTL32.DLL!ImageList_Destroy': 4,
  'COMCTL32.DLL!ImageList_EndDrag': 0,
  'IMM32.DLL!ImmNotifyIME': 16,
  'IMM32.DLL!ImmGetContext': 4,
  'IMM32.DLL!ImmGetCompositionStringA': 16,
  'IMM32.DLL!ImmSetOpenStatus': 8,
  'IMM32.DLL!ImmGetCandidateListA': 16,

  'BINKW32.DLL!_BinkSetSoundSystem@8': 8,
  'BINKW32.DLL!_BinkOpenDirectSound@4': 4,
  'BINKW32.DLL!_BinkGetError@0': 0,
  'BINKW32.DLL!_BinkOpen@8': 8,
  'BINKW32.DLL!_BinkSetVolume@8': 8,
  'BINKW32.DLL!_BinkClose@4': 4,
  'BINKW32.DLL!_BinkDDSurfaceType@4': 4,
  'BINKW32.DLL!_BinkGoto@12': 12,
  'BINKW32.DLL!_BinkPause@8': 8,
  'BINKW32.DLL!_BinkNextFrame@4': 4,
  'BINKW32.DLL!_BinkCopyToBuffer@28': 28,
  'BINKW32.DLL!_BinkDoFrame@4': 4,
  'BINKW32.DLL!_BinkWait@4': 4,

  'WINMM.DLL!waveOutRestart': 4,
  'WINMM.DLL!waveOutSetVolume': 8,
  'WINMM.DLL!waveOutUnprepareHeader': 12,
  'WINMM.DLL!waveOutPause': 4,
  'WINMM.DLL!waveOutReset': 4,
  'WINMM.DLL!waveOutPrepareHeader': 12,
  'WINMM.DLL!waveOutWrite': 12,
  'WINMM.DLL!waveOutOpen': 24,
  'WINMM.DLL!waveOutClose': 4,
  'GDI32.DLL!DeleteDC': 4,
  'GDI32.DLL!GetDIBits': 28,
  'GDI32.DLL!CreateCompatibleDC': 4,
  'GDI32.DLL!StretchBlt': 44,
  'GDI32.DLL!SetStretchBltMode': 8,
  'GDI32.DLL!CreateCompatibleBitmap': 12,
};

export function ra2Win32ArgBytes(dll: string, name: string): number {
  const key = `${dll.toUpperCase()}!${name}`;
  const bytes = RA2_ABI[key];
  if (bytes === undefined) throw new Error(`未登记的 Red Alert 2 Win32 ABI: ${key}`);
  return bytes;
}
